# This file tells Netlify how to build your frontend.
# It should be placed in the ROOT of your project (the main folder).

[build]
# Command:
# 1. Go into the rsmart-habit-builder folder
# 2. Run the build command
command = "cd rsmart-habit-builder && npm run build"

# Publish directory:
# The full path from the root of your project to the final built site.
publish = "rsmart-habit-builder/dist"

# Redirects rule for React Router
# This makes sure /login, /dashboard, etc. work on the live site.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

