# This file tells Netlify how to build your frontend.
# It must be in the ROOT of your GitHub repository.

[build]
  # Command to run:
  # 1. Navigates into the correct, deep folder
  # 2. Sets CI=false to ignore linter errors
  # 3. Runs the build
  command = "cd react-msdd/rsmart-habit-builder/rsmart-habit-builder && CI=false npm run build"
  
  # The folder that contains the final built website (relative to the root)
  publish = "react-msdd/rsmart-habit-builder/rsmart-habit-builder/dist"

  [build.environment]
    # Set the Node.js version to a modern one that Vite likes
    NODE_VERSION = "20"
    # This officially tells Netlify to ignore linter warnings
    CI = "false"
    # This is the NEW LINE: It tells Netlify to install devDependencies
    NPM_FLAGS = "--include=dev"

# This rule makes React Router (for pages like /login, /dashboard) work correctly.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

